---
# Command to run this playbook. make sure to change the IP of the host.
# ansible-playbook -i "xx.xx.xx.xx," -e 'ansible_ssh_user=ubuntu' r-users.yml --extra-vars "ansible_python_interpreter=/usr/bin/python3"
# Author: Alan Dickinson

# Command to test local ssh login with password. Make sure to change IP of host.
# ssh -o PubkeyAuthentication=no test6@xx.xx.xx.xx

# If you cant login with password check /etc/ssh/sshd_config for the entry
#   PasswordAuthentication no 
# change the entry to yes, save and restart ssh service
# service ssh restart

- hosts: all
  become: true

  tasks:
  - name: gather ec2 facts
    action: ec2_metadata_facts

# Hashed password created with mkpasswd
# Command used is "mkpasswd --method=sha-512"
  - name: add R users 
    user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      append: yes
      createhome: yes
      home: "/u/userhome/{{ item.name }}"
      state: present
      shell: /bin/bash
      update_password: on_create
    register: name
    with_items:
       - { name: username, password: '$6$nI0o24U7w$H0bdsFyUSwmr9B7QfJT7JmsLTqgAEmjsayN68/PMh1EUdxgodLHeRdmydO.Ssca3zwfEV/TCqbaZt1biE9hzD.'}
       
  - name: Force users to change password
    shell: chage -d 0 "{{ item.user }}"
    with_items:
      - { user: username }
    when: name.changed

  - name: add symlink to /home/username
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      state: link
    with_items:
       - { src: /u/userhome/username, dest: /home/username, owner: evilla, group: username }
